steps:
  - uses: actions/checkout@v3
   
  - name: Install
    run: npm ci
    working-directory: anthony-michael-photography v30

  - name: Build
    run: npm run build
    working-directory: anthony-michael-photography v30

  - name: Deploy
    run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
    working-directory: anthony-michael-photography v30