name: Build & Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1) Use Node.js 18 (or 20) so vite & crypto work
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 2) Install deps in the folder where your package.json lives
      - name: Install dependencies
        working-directory: anthony-site
        run: npm ci

      # 3) Build your site
      - name: Build
        working-directory: anthony-site
        run: npm run build

      # 4) Bring in the Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5) Deploy
      - name: Deploy to Firebase Hosting
        working-directory: anthony-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
