name: Build & Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        # 👇 run inside the anthony-website folder
        working-directory: anthony-website
        run: npm ci

      - name: Build with Vite
        # 👇 run inside the anthony-website folder
        working-directory: anthony-website
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        # 👇 your dist now lives at anthony-website/dist
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --project=anthony-michael-33b92 \
            --only hosting \
            --public anthony-website/dist
