name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Use Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies in the correct folder
      - name: Install dependencies
        working-directory: anthony-site
        run: npm ci

      # 4. Build your site
      - name: Build
        working-directory: anthony-site
        run: npm run build

      # 5. Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        working-directory: anthony-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
