jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        # remove this line if it says `working-directory: anthony-website`
        working-directory: .

      - name: Build
        run: npm run build
        working-directory: .

      - name: Deploy to Firebase
        run: firebase deploy --project anthony-michael-33b92 --token "${{ secrets.FIREBASE_TOKEN }}"
        working-directory: .

