name: Build & Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # allow checkout
      id-token: write       # allow minting OIDC token

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/903798418406/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deploy-sa@hardy-unison-464600-m6.iam.gserviceaccount.com

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: anthony-site
        run: npm ci

      - name: Build
        working-directory: anthony-site
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: anthony-site
        run: firebase deploy --only hosting
